# -*- mode: Makefile; -*-
# Generic makefile, do not use;

all:
	@echo "Please use the makefile for your OS:"
	@echo "            Linux: make -f makefile.unix"
	@echo "              OSX: make -f makefile.osx"
	@echo "   Windows+cygwin: make -f makefile.cygwin"

clean:
	rm -f ptsminer
	rm -f obj/*.o
